__title__ = '' # eg.) 'dnnet'
__description__ = '' # eg.) 'Deep Neural Network.'
__url__ = '' # eg.)'https://github.com/daichi-yoshikawa/dnnet'
__version__ = '1.0.0'
__author__ = ''
__author_email__ = ''
__license__ = '' # eg.) 'BSD-3-Clause'
__copyright__ = '' # eg.) 'Copyright (C) 2017 Daichi Yoshikawa'
